baseURL = "https://nicklafferty.com"
title = "Nick Lafferty"
theme = "manis"

# Copyright notice. Note: You can use HTML tag here
copyright = "&copy; 2020"
pluralizeListTitles = false

# Minimum number of posts before paginate navigation show up
paginate = 30

# Your disqus shortname
disqusShortname = ""

# Edit this if you want to translate your blog
defaultContentLanguage = "en"

# Google Analytics
googleAnalytics = "UA-41314241-2"

# Code Highlighting (Chroma)
pygmentsCodeFences = true
pygmentsUseClasses = true

[menu]
	[[menu.main]]
		name = "Blog"
		url = "/blog/"

    [[menu.main]]
		name = "Projects"
		url = "/projects"
        
    [[menu.main]]
        name = "Tags"
        url = "/tags"


[taxonomies]
	tag = "tags"

[params]
	# If false, use minified CSS (ui.min.css)
	debugCSS = false
	# Custom CSS
	customCSS = []
	
	# List of sections support disqus comments
	disqusSections = [ "blog" ]
	# Site meta description
	description = "Nick Lafferty | Personal blog for digital marketing, lead gen, and google sheets tips."
	# Site's Tagline (Subtitle or Keyword)
	tagline = "Digital Marketing & Lead Gen Expert"
	# If true give attribution to this theme
	themeAttrib = true
	# URL to license file, can be outside of your domain
	licenseURL = "/about/license"

	# Configure which section for Latest Posts
	postSection = "blog"
	# Configure which section for Latest Works
	workSection = ""

	# 404 Configuration
	head404 = "Sorry, I can't find what you want."
	sub404 = "Back to <a href='/'>Home</a>."

	# Color of your website's accent
	colorTheme = "#6441A4"
	# Maximum number of item in Latest Posts or Works
	latestCount = 8
	# Path to site's favicon image
	faviconImg = ""
	# Date format in item list
	dateFmt = "Jan 02, 2006"

	# Code Highlighting (HighlightJS)
	highlightJs = false
	highlightJsLanguages = [ "go" ]
	highlightJsStyle = "ocean"

	# Social Links
	email = "nick@lafferty.co"
	github = "https://github.com/NLaff"
	linkedin = "https://linkedin.com/in/nicklafferty"
    dev = "https://dev.to/nicklafferty"
    medium = "https://medium.com/@NickLafferty"

	enableRobotsTXT = true
	canonifyURLS = true

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 3


# Language Configuration
#[languages.in]
#	lang = "in"
#	languageName = "Bahasa Indonesia"
#	weight = 1
